const express = require('express')
// const path = require('path')
const shopController = require('../controllers/shop')
const route = express.Router()
const isAuth = require('../middleware/is-auth')
route.get('/', shopController.getIndex)
route.get('/product-list',shopController.getProducts)
route.get('/product-list/:productId',shopController.getProduct)
route.get('/cart', isAuth,shopController.getCart)
route.post('/cart', isAuth,shopController.postCart)
route.post('/cart-delete-item',isAuth,shopController.postCartDelete)
route.get('/checkout', isAuth, shopController.getCheckout)
route.get('/checkout/success',shopController.getCheckoutSuccess)
route.get('/checkout/cancel', shopController.getCheckout)
route.get('/orders',isAuth,shopController.getOrders)
route.get('/orders/:orderId',isAuth,shopController.getInvoice)

  module.exports = route